<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskPilot.Application\TaskPilot.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
      <PackageReference Include="Microsoft.Agents.AI" Version="1.16.0" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
      <PackageReference Include="OllamaSharp" Version="5.4.30" ExcludeAssets="analyzers" />
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.2" />
      <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.18.2" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    

</Project>
