import { FileText, GitBranch, History, X } from 'lucide-react';
import { useState } from 'react';
import type { Note } from '../../types/domain';

export function BacklinksPanel({ note, notes, onClose, onSelect }: { note: Note; notes: Note[]; onClose: () => void; onSelect: (id: number) => void }) {
  const [tab, setTab] = useState<'backlinks' | 'outgoing' | 'revisions'>('backlinks');
  const backlinks = notes.filter((candidate) => candidate.id !== note.id && candidate.content.includes(`[[${note.slug}`));
  const outgoing = [...note.content.matchAll(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g)].map((match) => ({ slug: match[1] ?? '', alias: match[2] }));
  return <aside className="backlinks-panel"><header><div><span className="eyebrow">NOT BAĞLANTILARI</span><strong>{note.title}</strong></div><button className="icon-button" onClick={onClose} aria-label="Bağlantı panelini kapat"><X /></button></header><div className="panel-tabs"><button className={tab === 'backlinks' ? 'is-active' : ''} onClick={() => setTab('backlinks')}><GitBranch />Backlinks</button><button className={tab === 'outgoing' ? 'is-active' : ''} onClick={() => setTab('outgoing')}><FileText />Giden</button><button className={tab === 'revisions' ? 'is-active' : ''} onClick={() => setTab('revisions')}><History />Sürümler</button></div><div className="backlinks-panel__body">{tab === 'backlinks' ? backlinks.map((item) => <button className="link-card" onClick={() => onSelect(item.id)} key={item.id}><strong>{item.title}</strong><span>/{item.slug}</span></button>) : null}{tab === 'outgoing' ? outgoing.map((item) => { const target = notes.find((candidate) => candidate.slug === item.slug); return <button className={`link-card${target ? '' : ' link-card--unresolved'}`} onClick={() => target && onSelect(target.id)} key={item.slug}><small>{target ? 'RESOLVED' : 'UNRESOLVED'}</small><strong>{item.alias ?? item.slug}</strong><span>[[{item.slug}]]</span></button>; }) : null}{tab === 'revisions' ? Array.from({ length: Math.min(4, note.version) }, (_, index) => <div className="revision" key={index}><span /><div><strong>v{note.version - index}</strong><p>{index ? 'Önceki içerik sürümü' : 'Mevcut sürüm'}</p></div></div>) : null}{tab === 'backlinks' && !backlinks.length ? <p className="quiet-copy">Bu nota bağlanan başka bir not yok.</p> : null}</div></aside>;
}
